package models

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"time"
)

// PasswordResetToken is a single-use, time-limited token that allows a user to
// set a new password without knowing their current one. Tokens are generated by
// an admin and expire 30 minutes after creation.
type PasswordResetToken struct {
	Token     string
	Username  string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

// Valid returns true when the token has not been used and has not expired.
func (t *PasswordResetToken) Valid() bool {
	if t.UsedAt != nil {
		return false
	}
	return time.Now().Before(t.ExpiresAt)
}

// PasswordResetTokenStore manages password-reset tokens in the shared users DB.
type PasswordResetTokenStore struct {
	db *sql.DB
}

// NewPasswordResetTokenStore creates a PasswordResetTokenStore.
func NewPasswordResetTokenStore(db *sql.DB) *PasswordResetTokenStore {
	return &PasswordResetTokenStore{db: db}
}

// Generate creates a new 30-minute reset token for the given username.
func (s *PasswordResetTokenStore) Generate(username string) (string, error) {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	token := hex.EncodeToString(b)
	expiresAt := time.Now().UTC().Add(30 * time.Minute)

	_, err := s.db.ExecContext(
		context.Background(),
		`INSERT INTO password_reset_tokens (token, username, expires_at) VALUES (?, ?, ?)`,
		token, username, expiresAt,
	)
	if err != nil {
		return "", err
	}
	return token, nil
}

// GetValid returns a token record only when it exists, has not been used, and
// has not expired.
func (s *PasswordResetTokenStore) GetValid(token string) (*PasswordResetToken, error) {
	rt := &PasswordResetToken{}
	var usedAt sql.NullTime
	err := s.db.QueryRowContext(
		context.Background(),
		`SELECT token, username, expires_at, used_at, created_at
		 FROM password_reset_tokens WHERE token = ?`,
		token,
	).Scan(&rt.Token, &rt.Username, &rt.ExpiresAt, &usedAt, &rt.CreatedAt)
	if err != nil {
		return nil, err
	}
	if usedAt.Valid {
		rt.UsedAt = &usedAt.Time
	}
	if !rt.Valid() {
		return nil, sql.ErrNoRows
	}
	return rt, nil
}

// Consume marks the token as used. Must be called immediately after the
// password has been updated.
func (s *PasswordResetTokenStore) Consume(token string) error {
	res, err := s.db.ExecContext(
		context.Background(),
		`UPDATE password_reset_tokens SET used_at = ? WHERE token = ? AND used_at IS NULL`,
		time.Now().UTC(), token,
	)
	if err != nil {
		return err
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return sql.ErrNoRows
	}
	return nil
}
